services:
  local-database:
    image: "postgres:latest"
    env_file:
      - environment.env
    ports:
      - "5432:5432"
    volumes:
      - pg-volume:/var/lib/postgresql/data/

volumes:
  pg-volume: { }
