server:
  port: 8080

logging:
  level:
    org.springframework.security: TRACE

spring:
  application:
    name: calories
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  messages:
    basename: "messages,config.i18n.messages"
    fallback-to-system-locale: false
  datasource:
    url: jdbc:postgresql://localhost:5432/calories
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  exposed:
    generate-ddl: false
    show-sql: true

FIREBASE_API_KEY: ${FIREBASE_API_KEY}
